image: 'node:15.12-alpine'

stages:
  - test

lint:
  stage: test
  before_script:
    - npm i
  script:
    - npm run lint
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull-push

jest:
  stage: test
  before_script:
    - npm i
  script:
    - npm run test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull-push
