image: 'node:15.12.0'

stages:
  - setup
  - test

node:install:
  stage: setup
  script:
    - npm i
    - echo $CI_COMMIT_REF_SLUG
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull-push
  artifacts:
    paths:
      - node_modules/

lint:
  stage: test
  script:
    - npm run lint
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull-push

jest:
  stage: test
  script:
    - npm run jest
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull-push
