name: Android

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install npm dependencies
      run: npm ci
    - name: Install fastlane
      run: bundle install
    - name: Build the app
      run: bundle exec fastlane build
      working-directory: android
