name: iOS

on: [push]

jobs:
  build_ios:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Set up environment (dependencies, Xcode project)
        run: scripts/setup --ios --ci
      - name: Build the app
        run: bundle exec fastlane build_only
        working-directory: ios
